import Head from "next/head";
import {
  FieldValues,
  UseFormRegister,
} from "react-hook-form";
import { useEffect, useState } from "react";
import BasicInformation from "../../../components/merchant/register/BasicInformation";

export type InputProps = {
  register: UseFormRegister<FieldValues>;
  errors: any;
  name: string;
};

export default function Register() {
  const [formData, setFormData] = useState({});
  const [activeIndex, setActiveIndex] = useState(0);

  useEffect(() => {
    console.log(formData)
  },[formData])

  return (
    <>
      <Head>
        <title>Register Data</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" ref="/favicon.ico" />
      </Head>
      {
        {
            0: <BasicInformation setFormData={setFormData} formData={formData} />,
        }[0]
      }
    </>
  );
}
