import Head from "next/head";
import {
  FieldValues,
  UseFormRegister,
} from "react-hook-form";
import { useEffect, useState } from "react";
import BasicInformation from "../../../components/merchant/register/BasicInformation";
import { getServerSession } from "next-auth";
import { authOptions } from "../../../server/auth";

export type InputProps = {
  register: UseFormRegister<FieldValues>;
  errors: any;
  name: string;
};

export async function getServerSideProps(context: { req: any; res: any }) {
  const session = await getServerSession(context.req, context.res, authOptions);

  console.log(session?.user)

  if (!session) {
    return {
      redirect: {
        destination: "/login?callbackUrl=/merchant",
        permanent: false,
      },
    };
  }

  if(session.user.merchantId){
    return {
      redirect: {
        destination: "/merchant",
        permanent: false,
      },
    };
  }

  return {
    props: {
      session,
    },
  };
}

export default function Register() {
  const [formData, setFormData] = useState({});
  const [activeIndex, setActiveIndex] = useState(0);



  useEffect(() => {
    console.log(formData)
  },[formData])

  return (
    <>
      <Head>
        <title>Register Data</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" ref="/favicon.ico" />
      </Head>
      {
        {
            0: <BasicInformation setFormData={setFormData} formData={formData} />,
        }[0]
      }
    </>
  );
}
