import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

const Prepare = ({ setActiveIndex }: any) => {
  return (
    <>
      <Head>
        <title>Prepare your documents</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen flex-col justify-between px-8 ">
        <div className="flex flex-col items-center pt-20">
          <p className="w-80 text-center text-4xl font-bold tracking-widest text-red-600">
            GAS! Driver
          </p>
          <p className="text-s pt-2 font-bold tracking-wider">
            Become a GAMA Driver now
          </p>
        </div>
        <div className="flex flex-col items-center mb-8 ">
          <p className="pb-4 text-base font-bold tracking-wider text-gray-900">
            Prepare The Following Documents
          </p>
          <div className="h-64 w-80 rounded-lg bg-white p-6 shadow-2xl">
            <div className="inline-flex">
              <Image
                src="/user-data.png"
                alt="prepare"
                width={35}
                height={35}
              />
              <p className="flex items-center pl-2 text-base font-medium tracking-wider text-gray-900">
                ID (KTP)
              </p>
            </div>

            <div className="inline-flex pt-3">
              <Image
                className="object-contain"
                src="/bank-account.png"
                alt="prepare"
                width={35}
                height={35}
              />
              <p className="flex items-center pt-2 pl-2 text-base font-medium tracking-wider text-gray-900">
                Bank Account Number
              </p>
            </div>
            <div className="inline-flex pt-3">
              <Image
                className="object-contain"
                src="/registration.png"
                alt="prepare"
                width={35}
                height={35}
              />
              <p className="flex items-center pl-2 text-base font-medium tracking-wider text-gray-900">
                Vehicle Registration (STNK)
              </p>
            </div>
            <div className="inline-flex pt-3">
              <Image
                className="object-contain"
                src="/driver-license.png"
                alt="prepare"
                width={35}
                height={35}
              />
              <p className="flex items-center pl-2 text-base font-medium tracking-wider text-gray-900">
                Drivers License
              </p>
            </div>
          </div>
        </div>
        <button onClick={() => setActiveIndex(3)} className="mb-16 inline-flex h-14 w-full items-center justify-center rounded-md border bg-red-600 py-3.5 px-28 text-xl font-bold text-white">
          Proceed
        </button>
      </main>
    </>
  );
};

export default Prepare;
