import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "../utils/api";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-between bg-gradient-to-b px-8 py-32 ">
        <div className="">
          <h1 className=" text-4xl font-bold">Gas! Merchant</h1>
          <h2 className=" "> Become a GaMa merchant now!</h2>
        </div>
        <button
          className="  h-14 w-full text-white rounded-xl bg-indigo-400 text-lg font-bold"
          onClick={() => {
            signIn();
          }}
        >
          Log In
        </button>
      </main>
    </>
  );
};

export default Home;
