import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { IoPersonOutline } from "react-icons/io5";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Welcome to GaMa</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Image className="-z-10 object-cover" src="/bg_login.png" alt="bg" fill/>
        <div className="inline-flex w-full justify-center items-center p-12 pt-32">
          <Image
            className="drop-shadow-xl rounded-3xl"
            src="/gama-logo2.png"
            width={100}
            height={100}
            alt="logo"
          />
          <p className="flex flex-col pl-4 text-4xl  font-black text-red-500">
            GAS! Madhang
          </p>
        </div>
        <p className="text-center text-2xl font-extrabold tracking-widest text-gray-900">
          Who Are You?
        </p>
        <div className="mx-auto mt-6 flex h-56 w-80 rounded-2xl bg-white shadow-xl">
          <div className="h-12 w-70 mx-auto mt-5">
            <Link href={"/customer"}>
                <div className="flex h-full rounded-xl bg-red-500 py-3 px-20">
                  <p className="h-full flex-1 text-center text-xl font-bold tracking-widest text-gray-50">
                    Customer
                  </p>
                </div>
            </Link>
            <Link href={"/merchant"}>
                <div className="mt-5 flex h-full rounded-xl bg-red-500 py-3 px-20">
                  <p className="h-full flex-1 text-center text-xl font-bold tracking-widest text-gray-50">
                    Merchant
                  </p>
                </div>
            </Link>
            <Link href={"/driver"}>
                <div className="mt-5 flex h-full rounded-xl bg-red-500 py-3 px-20">
                  <p className="h-full flex-1 text-center text-xl font-bold tracking-widest text-gray-50">
                    Driver
                  </p>
                </div>
            </Link>

          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
