import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>

        <title>Welcome to GaMa</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex flex-col items-center py-40">
          <p className="flex w-auto flex-col items-center text-3xl font-bold tracking-widest text-gray-900">
            GAS! Platform
          </p>
          <p className="pt-2 text-s font-bold tracking-wider">
            Welcome To Gama Platform
          </p>
          <p className="pt-2 text-s font-bold tracking-wider">
            Gas Makan Sampe Kenyang
          </p>
        </div>
        <div className="flex justify-center">
          <Link href={"/customer"}>
            <div className="flex h-14 w-72 flex-1 items-center justify-center space-x-2 rounded-md border border-gray-600 bg-slate-800">
              <img
                className="h-8 w-8"
                src="https://via.placeholder.com/34x29"
              />
              <p className="text-xl font-bold tracking-widest text-white">
                Customer
              </p>
            </div>
          </Link>
        </div>
        <div className="flex justify-center pt-3">
          <Link href={"/driver"}>
            <div className="flex h-14 w-72 flex-1 items-center justify-center space-x-2 rounded-md border border-gray-600 bg-slate-800">
              <img
                className="h-8 w-8"
                src="https://via.placeholder.com/34x29"
              />
              <p className="text-xl font-bold tracking-widest text-white">
                Driver
              </p>
            </div>
          </Link>
        </div>
        <div className="flex justify-center pt-3">
          <Link href={"/merchant"}>
            <div className="flex h-14 w-72 flex-1 items-center justify-center space-x-2 rounded-md border border-gray-600 bg-slate-800">
              <img
                className="h-8 w-8"
                src="https://via.placeholder.com/34x29"
              />
              <p className="text-xl font-bold tracking-widest text-white">
                Merchant
              </p>
            </div>
          </Link>
        </div>
      </main>
    </>
  );
};

export default Home;
